export const products = [
    {
        id: 1,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 2,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 3,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 4,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 5,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 6,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 7,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 8,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 9,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 10,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 11,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 12,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 13,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 14,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 15,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 16,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 17,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 18,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 19,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 20,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 21,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 22,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 23,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 24,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 25,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 26,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 27,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
    {
        id: 28,
        title: 'Mens summer t shirt',
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit, sed diam nonumy eirmod tempor invid id vel dui sed diam nonumy eirmod tempor invid id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel duis sed diam nonumy eirmod tempor inv id vel du ist aliquet vel non pro id vel duis sed diam nonumy eirmod tempor inv id vel du is t al quis et justo al ea commodo consequ',
        price: 500,
        inStock: 10,
        discount: 20,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        images: ['image', 'image1', 'image2', 'image3'],
        coupon: [
            { id: 1, code: 'joy', discount: 30 },
            { id: 2, code: 'kkk', discount: 20 },
        ],
        category: { mainCat: 'Mens fashion', subCat: 't-shirt' },
        color: ['red', 'green', 'yellow'],
        reviews: [
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
            {
                id: 1,
                review: 'lorem Ips incorrectly formatted incorrectly hello world world world kiklorem Ips incorrectly formatted incorrectly',
                username: 'joy',
                userId: 1023240,
                rating: 4,
            },
        ],
        gender: ['men', 'women', 'baby'],
        brand: 'Top Ten',
        specification: 'lorem ispun hello kgellko jkadsfjh adslfjl',
        tags: ['mens', 'womens'],
        warranty: '3 Months from purchasing',
        returnPolicy: 'No return if there is any physical damage',
    },
];
